import { deriveRules } from "../packages/datum/src/rules/index.js";
const r = await deriveRules({ dir: "/Users/jish/Documents/GitHub/arc", repo: "aeonmindai/arc", scope: "org/a/proj/arc" });
const f = r.unenforced;
const idx = (p:(x:any)=>boolean) => { const i = f.findIndex(p); return i<0 ? "MISSING" : `rank ${i+1}`; };
console.log("cudnn ban:", idx(x=>x.target==="cudnn"));
for (const x of f.filter(x=>x.target==="cudnn")) console.log(`   ${x.source} [${x.strength}] d=${x.doctrinal} also=${x.also_at.length} "${x.statement.slice(0,90)}" target=${x.target}`);
console.log("W=256 ban:", idx(x=>/w=256/.test(x.target)));
for (const x of f.filter(x=>/w=256/.test(x.target)).slice(0,4)) console.log(`   ${x.source} [${x.strength}] d=${x.doctrinal} "${x.statement.slice(0,90)}" target=${x.target}`);
console.log("greedy ban:", idx(x=>x.target==="greedy"));
for (const x of f.filter(x=>x.target==="greedy").slice(0,3)) console.log(`   ${x.source} [${x.strength}] d=${x.doctrinal} "${x.statement.slice(0,90)}"`);
console.log("\nGPU_ACCESS_RULE.md findings:", f.filter(x=>x.file==="memory/GPU_ACCESS_RULE.md").map(x=>`${x.line}/${x.target}`).join(" "));
console.log("\nTOP 10 FINAL:");
f.slice(0,10).forEach((x,i)=>console.log(`${i+1}. [${x.strength}] ${x.source}  d=${x.doctrinal} also=${x.also_at.length}\n   heading: ${x.heading}\n   "${x.statement.slice(0,150)}"\n   target: ${x.target} | ${x.why}`));
