/**
 * What the walker refuses to look at, and what the resolver refuses to treat as a call.
 */

/**
 * Directory names skipped before descending, matched at any depth.
 *
 * `.claude` is the load-bearing one and the reason this list is a hard default rather than
 * documentation. On the Arc corpus `.claude/worktrees` holds up to 34 near-complete copies of the
 * source tree; walking it would give almost every symbol a set of duplicates, collapsing
 * `unique-name` into `ambiguous-name` across the whole index and destroying the signal that impact
 * analysis is built on. `target`, `node_modules`, `dist` and `build` are the same failure in
 * miniature: vendored or generated code that answers questions about someone else's repository.
 */
const SKIPPED_DIRECTORY_NAMES = [
  ".git",
  ".claude",
  "node_modules",
  "target",
  "dist",
  "build",
  ".venv",
  "venv",
  "__pycache__",
  ".pytest_cache",
  ".mypy_cache",
  ".cargo",
  ".idea",
  ".vscode",
] as const;

export const SKIP_DIRS: ReadonlySet<string> = new Set(SKIPPED_DIRECTORY_NAMES);

/** Extension to language. The key set is also the definition of "a file worth parsing". */
export const LANGUAGE_BY_EXTENSION = {
  ".rs": "rust",
  ".py": "python",
  ".pyi": "python",
  ".c": "c",
  ".h": "c",
  ".cc": "cpp",
  ".cpp": "cpp",
  ".cxx": "cpp",
  ".hpp": "cpp",
  ".hh": "cpp",
  ".hxx": "cpp",
  ".cu": "cuda",
  ".cuh": "cuda",
} as const;

/**
 * Names that appear in call position but are not calls into this codebase.
 *
 * Without this the graph fills with noise, and the noise is not harmless: `.unwrap()` alone would
 * contribute hundreds of thousands of `unresolved` edges on a Rust corpus, which makes the
 * resolution histogram — the thing we judge index quality by — unreadable, and inflates the store
 * for zero decision value.
 *
 * The list is deliberately conservative, because the two failure modes are not symmetric. Filtering
 * too little only adds `unresolved` edges, which the histogram makes visible and which a reader can
 * discount. Filtering too much silently deletes a real edge, and a missing edge in an impact answer
 * is exactly the kind of quiet wrongness this product exists to refuse. So: language keywords,
 * genuine builtins, and the standard-library vocabulary that overwhelmingly dominates each
 * language. No attempt is made to cover third-party ecosystems (numpy, torch, tokio) — a
 * project-local method that happens to share a name with one of those keeps its edge.
 *
 * The known cost: a project-local function genuinely named `len`, `get` or `find` loses its
 * incoming edges. That trade is worth taking because those names are std vocabulary two or three
 * orders of magnitude more often than they are local definitions.
 */
const NON_CALL_TARGET_NAMES = [
  // Control flow and keywords that the grammars can surface in call position, especially inside
  // ERROR nodes where a construct did not parse cleanly.
  "if",
  "else",
  "for",
  "while",
  "loop",
  "match",
  "switch",
  "case",
  "return",
  "break",
  "continue",
  "yield",
  "await",
  "async",
  "try",
  "catch",
  "throw",
  "raise",
  "with",
  "as",
  "in",
  "is",
  "not",
  "and",
  "or",
  "sizeof",
  "typeof",
  "alignof",
  "typeid",
  "decltype",
  "static_assert",
  "assert",
  "defined",

  // Rust: prelude macros. `vec!`, `format!` and the assert family are the top macro invocations in
  // any Rust corpus and none of them is a local definition.
  "vec",
  "format",
  "println",
  "eprintln",
  "print",
  "eprint",
  "write",
  "writeln",
  "panic",
  "todo",
  "unimplemented",
  "unreachable",
  "assert_eq",
  "assert_ne",
  "debug_assert",
  "debug_assert_eq",
  "debug_assert_ne",
  "matches",
  "dbg",
  "include_str",
  "include_bytes",
  "concat",
  "stringify",
  "env",
  "option_env",
  "cfg",
  "line",
  "column",
  "file",
  "module_path",
  "thread_local",
  "lazy_static",

  // Rust: the Option/Result/Iterator/collection vocabulary. These dominate call sites and never
  // resolve locally, because std is not in the index.
  "unwrap",
  "expect",
  "unwrap_or",
  "unwrap_or_else",
  "unwrap_or_default",
  "unwrap_err",
  "expect_err",
  "ok",
  "ok_or",
  "ok_or_else",
  "err",
  "is_some",
  "is_none",
  "is_ok",
  "is_err",
  "and_then",
  "or_else",
  "map_err",
  "map_or",
  "map_or_else",
  "clone",
  "cloned",
  "copied",
  "into",
  "to_owned",
  "to_string",
  "to_vec",
  "as_str",
  "as_ref",
  "as_mut",
  "as_slice",
  "as_mut_slice",
  "as_bytes",
  "as_deref",
  "borrow",
  "borrow_mut",
  "iter",
  "iter_mut",
  "into_iter",
  "next",
  "next_back",
  "map",
  "filter",
  "filter_map",
  "flat_map",
  "flatten",
  "fold",
  "try_fold",
  "for_each",
  "collect",
  "enumerate",
  "zip",
  "rev",
  "take",
  "take_while",
  "skip",
  "skip_while",
  "chain",
  "any",
  "all",
  "find",
  "find_map",
  "position",
  "sum",
  "product",
  "count",
  "last",
  "peekable",
  "peek",
  "step_by",
  "windows",
  "chunks",
  "chunks_exact",
  "sort",
  "sort_by",
  "sort_by_key",
  "sort_unstable",
  "sort_unstable_by",
  "dedup",
  "retain",
  "truncate",
  "extend",
  "extend_from_slice",
  "push",
  "pop",
  "push_str",
  "append",
  "drain",
  "splice",
  "split_off",
  "swap",
  "swap_remove",
  "reverse",
  "fill",
  "len",
  "is_empty",
  "capacity",
  "with_capacity",
  "reserve",
  "clear",
  "contains",
  "contains_key",
  "get_or_insert",
  "entry",
  "or_insert",
  "or_insert_with",
  "or_default",
  "keys",
  "values",
  "values_mut",
  "trim",
  "trim_start",
  "trim_end",
  "split",
  "splitn",
  "rsplit",
  "split_whitespace",
  "split_once",
  "rsplit_once",
  "join",
  "lines",
  "chars",
  "char_indices",
  "starts_with",
  "ends_with",
  "strip_prefix",
  "strip_suffix",
  "replace",
  "replacen",
  "repeat",
  "to_lowercase",
  "to_uppercase",
  "to_ascii_lowercase",
  "to_ascii_uppercase",
  "parse",
  "abs",
  "signum",
  "sqrt",
  "cbrt",
  "recip",
  "exp",
  "ln",
  "log",
  "log2",
  "log10",
  "powi",
  "powf",
  "floor",
  "ceil",
  "round",
  "trunc",
  "clamp",
  "min",
  "max",
  "mul_add",
  "is_nan",
  "is_finite",
  "is_infinite",
  "saturating_add",
  "saturating_sub",
  "saturating_mul",
  "checked_add",
  "checked_sub",
  "checked_mul",
  "checked_div",
  "wrapping_add",
  "wrapping_sub",
  "wrapping_mul",
  "div_ceil",
  "next_power_of_two",
  "leading_zeros",
  "trailing_zeros",
  "count_ones",
  "lock",
  "read",
  "write_all",
  "flush",
  "send",
  "recv",
  "spawn",
  "join_all",
  "deref",
  "deref_mut",
  "drop",
  "default",
  "fmt",
  "hash",
  "eq",
  "ne",
  "cmp",
  "partial_cmp",
  "then",
  "then_some",

  // Python builtins and exception constructors.
  "len",
  "range",
  "sorted",
  "reversed",
  "abs",
  "round",
  "int",
  "float",
  "str",
  "bool",
  "list",
  "dict",
  "set",
  "tuple",
  "frozenset",
  "bytes",
  "bytearray",
  "memoryview",
  "complex",
  "object",
  "type",
  "isinstance",
  "issubclass",
  "getattr",
  "setattr",
  "hasattr",
  "delattr",
  "callable",
  "open",
  "super",
  "repr",
  "id",
  "hash",
  "iter",
  "next",
  "slice",
  "dir",
  "vars",
  "globals",
  "locals",
  "eval",
  "exec",
  "compile",
  "input",
  "ord",
  "chr",
  "hex",
  "oct",
  "bin",
  "divmod",
  "pow",
  "staticmethod",
  "classmethod",
  "property",
  "Exception",
  "BaseException",
  "ValueError",
  "TypeError",
  "KeyError",
  "IndexError",
  "RuntimeError",
  "NotImplementedError",
  "AttributeError",
  "StopIteration",
  "ZeroDivisionError",
  "OSError",
  "IOError",
  "ImportError",
  "AssertionError",
  "FileNotFoundError",
  "OverflowError",

  // Python: the container/string/file method vocabulary.
  "items",
  "update",
  "setdefault",
  "add",
  "discard",
  "remove",
  "index",
  "copy",
  "close",
  "readline",
  "readlines",
  "writelines",
  "seek",
  "tell",
  "encode",
  "decode",
  "lower",
  "upper",
  "strip",
  "lstrip",
  "rstrip",
  "lstrip",
  "rjust",
  "ljust",
  "zfill",
  "startswith",
  "endswith",
  "rsplit",
  "splitlines",
  "partition",
  "rpartition",
  "casefold",
  "title",
  "capitalize",

  // C / C++ / CUDA: libc, the STL vocabulary, and CUDA runtime + intrinsics.
  "printf",
  "fprintf",
  "sprintf",
  "snprintf",
  "malloc",
  "calloc",
  "realloc",
  "free",
  "memcpy",
  "memset",
  "memmove",
  "memcmp",
  "strlen",
  "strcpy",
  "strncpy",
  "strcmp",
  "strncmp",
  "strcat",
  "abort",
  "exit",
  "fopen",
  "fclose",
  "fread",
  "fwrite",
  "size",
  "begin",
  "end",
  "cbegin",
  "cend",
  "rbegin",
  "rend",
  "push_back",
  "pop_back",
  "emplace",
  "emplace_back",
  "data",
  "resize",
  "at",
  "front",
  "back",
  "empty",
  "insert",
  "erase",
  "make_unique",
  "make_shared",
  "make_pair",
  "make_tuple",
  "move",
  "forward",
  "swap",
  "get",
  "value",
  "value_or",
  "has_value",
  "reset",
  "release",
  "lock_guard",
  "unique_lock",
  "sqrtf",
  "expf",
  "logf",
  "powf",
  "fabs",
  "fabsf",
  "fminf",
  "fmaxf",
  "fmod",
  "floorf",
  "ceilf",
  "roundf",
  "rintf",
  "tanhf",
  "erff",
  "sinf",
  "cosf",
  "__syncthreads",
  "__syncwarp",
  "__threadfence",
  "__shfl_sync",
  "__shfl_up_sync",
  "__shfl_down_sync",
  "__shfl_xor_sync",
  "__ballot_sync",
  "__popc",
  "__clz",
  "__ffs",
  "__brev",
  "__ldg",
  "__expf",
  "__logf",
  "__fmaf_rn",
  "__fdividef",
  "__float2half",
  "__half2float",
  "__hadd",
  "__hmul",
  "__hfma",
  "atomicAdd",
  "atomicMax",
  "atomicMin",
  "atomicCAS",
  "atomicExch",
  "make_float2",
  "make_float4",
  "make_int2",
  "make_int4",
  "cudaMalloc",
  "cudaFree",
  "cudaMemcpy",
  "cudaMemcpyAsync",
  "cudaMemset",
  "cudaGetLastError",
  "cudaDeviceSynchronize",
  "cudaStreamSynchronize",
  "cudaFuncSetAttribute",
  "cudaGetDeviceProperties",
] as const;

export const NON_CALL_TARGETS: ReadonlySet<string> = new Set(NON_CALL_TARGET_NAMES);

/**
 * Built-in types. Excluded from `uses_type` edges: a signature mentioning `u32` or `float` tells us
 * nothing about the shape of this repository, and including them would make the type edges an
 * arbitrarily large multiple of the interesting ones.
 */
const BUILTIN_TYPE_NAMES = [
  "u8",
  "u16",
  "u32",
  "u64",
  "u128",
  "usize",
  "i8",
  "i16",
  "i32",
  "i64",
  "i128",
  "isize",
  "f16",
  "f32",
  "f64",
  "bool",
  "char",
  "str",
  "String",
  "Self",
  "Vec",
  "Box",
  "Option",
  "Result",
  "Arc",
  "Rc",
  "RefCell",
  "Cell",
  "Mutex",
  "RwLock",
  "HashMap",
  "HashSet",
  "BTreeMap",
  "BTreeSet",
  "VecDeque",
  "Cow",
  "PathBuf",
  "Path",
  "OsString",
  "OsStr",
  "Duration",
  "Instant",
  "Ordering",
  "void",
  "int",
  "long",
  "short",
  "float",
  "double",
  "unsigned",
  "signed",
  "size_t",
  "ssize_t",
  "ptrdiff_t",
  "intptr_t",
  "uintptr_t",
  "int8_t",
  "int16_t",
  "int32_t",
  "int64_t",
  "uint8_t",
  "uint16_t",
  "uint32_t",
  "uint64_t",
  "half",
  "half2",
  "nv_bfloat16",
  "__half",
  "__half2",
  "__nv_bfloat16",
  "float2",
  "float3",
  "float4",
  "int2",
  "int3",
  "int4",
  "uchar4",
  "dim3",
  "cudaStream_t",
  "cudaError_t",
  "FILE",
  "None",
  "Any",
  "Optional",
  "Union",
  "List",
  "Dict",
  "Set",
  "Tuple",
  "Callable",
  "Iterator",
  "Iterable",
  "Sequence",
  "Mapping",
] as const;

export const BUILTIN_TYPES: ReadonlySet<string> = new Set(BUILTIN_TYPE_NAMES);

/**
 * Receiver node types that mean "this is a method on a primitive or a literal", e.g. `1.max(x)` or
 * `"s".len()`. Nothing local is ever on the other end of those.
 */
const LITERAL_RECEIVER_TYPES = [
  "integer_literal",
  "float_literal",
  "string_literal",
  "char_literal",
  "boolean_literal",
  "raw_string_literal",
  "byte_string_literal",
  "number_literal",
  "string",
  "concatenated_string",
  "integer",
  "float",
  "true",
  "false",
  "none",
  "primitive_type",
  "char",
  "number",
] as const;

export const LITERAL_RECEIVERS: ReadonlySet<string> = new Set(LITERAL_RECEIVER_TYPES);

/**
 * Above this many same-named symbols the edge is recorded as `unresolved` rather than as an
 * ambiguous edge carrying the whole candidate set.
 *
 * "It is one of these 300 methods called `new`" carries no decision value for an impact answer, and
 * a 300-element candidate array per edge would bloat the store for nothing. The count of edges
 * demoted this way is reported in `stats.resolution_ambiguity_ceiling`, so the decision is
 * auditable and never silently conflated with a genuine not-found — `dst_name` still records what
 * was called.
 */
export const AMBIGUITY_CEILING = 8;
